<a href="https://colab.research.google.com/github/stevengregori92/LearnRecSys/blob/main/Content_Based_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import word_tokenize

import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
!gdown https://drive.google.com/uc?id=1kF6d9bJnZjehyPeoh6ixMETJnYbjFC3I
!unzip /content/rec.zip

Downloading...
From: https://drive.google.com/uc?id=1kF6d9bJnZjehyPeoh6ixMETJnYbjFC3I
To: /content/rec.zip
100% 18.1M/18.1M [00:00<00:00, 41.7MB/s]
Archive:  /content/rec.zip
  inflating: collaborative_filtering.csv  
  inflating: content_by_multiple.csv  
  inflating: content_by_synopsis.csv  
  inflating: demographic.csv         


#Content = Overiview

In [ ]:
df = pd.read_csv('content_by_synopsis.csv')
df.head()

title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview  
0  Led by Woody, Andy's toys live happily in his ...  
1  When siblings Judy and Peter discover an encha...  
2  A family wedding reignites the ancient feud be...  
3  Cheated on, mistreated and stepped on, the wom...  
4  Just when George Banks has recovered from his ...

#Encode all bank

In [ ]:
bow = CountVectorizer(stop_words='english', tokenizer=word_tokenize)
bank = bow.fit_transform(df.overview)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


#Step 1: Encode What Users Watch

In [ ]:
idx=0

In [ ]:
content = df.loc[idx, 'overview']
content

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [ ]:
code = bow.transform([content])
code

<1x86599 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

#Step 2: Document Search

In [ ]:
from sklearn.metrics.pairwise import cosine_distances

In [ ]:
dist = cosine_distances(code, bank)
dist

array([[0.        , 0.68698928, 0.70198022, ..., 0.88529213, 0.68931574,
        0.75277431]])

In [ ]:
dist.argsort()

array([[    0, 14706,  2945, ..., 13763, 34258, 29249]])

In [ ]:
rec_idx = dist.argsort()[0, 1:11]
rec_idx

array([14706,  2945,  9984, 36827, 40606, 13404, 22084, 14078,  6172,
       27006])

#Step 3: Recommend

In [ ]:
df.loc[rec_idx]

title  \
14706                      Toy Story 3   
2945                       Toy Story 2   
9984            The 40 Year Old Virgin   
36827                    Wabash Avenue   
40606                           Stasis   
13404              The Gang's All Here   
22084                   The Pied Piper   
14078              A Matter of Dignity   
6172   The Courtship of Eddie's Father   
27006                        Superdome   

                                                overview  
14706  Woody, Buzz, and the rest of Andy's toys haven...  
2945   Andy heads off to Cowboy Camp, leaving his toy...  
9984   Andy Stitzer has a pleasant life with a nice a...  
36827  Andy Clark discovers he was cheated out of a h...  
40606  After a night out of partying and left behind ...  
13404  Playboy Andy Mason, on leave from the army, ro...  
22084  Greed, corruption, ignorance, and disease. Mid...  
14078  During one of her parents many parties, Chloe ...  
6172   The film that started the classic TV series. A...  
27006  It's Superbowl. And there's a lot of drama, on...